name: chocolatine
run-name: ${{ github.actor }} is eating a chocolatine

on:
  push:
    branches-ignore: "ga-ignore-*"
  pull_request:
    branches-ignore: "ga-ignore-*"

env:
  EXECUTABLES: ""
  MIRROR_URL: ""

jobs:
  install_dependencies:
    steps:
    - run: nmp install
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
    - run: | 
        check.sh $(pwd) $(pwd)
        if [ -s coding-style-report.log ]; then
          exit 0
        fi
        echo "::error::" | cat coding-style-reports.log
  check_program_compilation:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v4
      run: make
      run: make clean