name: chocolatine

on:
  push:
    branches-ignore: "ga-ignore-*"
  pull_request:
    branches-ignore: "ga-ignore-*"

env:
  EXECUTABLES: ""
  MIRROR_URL: ""

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fect-depth: 0
      - name: coding_style_checker
        run: |
          check.sh $(pwd) $(pwd)
          if [ -s coding-style-report.log ]; then
          exit 0
          fi
          echo "::error::" | cat coding-style-reports.log
          exit 1

  check_program_compilation:
    needs: [check_coding_style]
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
        with:
          fect-depth: 0
      - name: make
        timeout-minutes: 2
        run: |
          make
      - name: make clean
        run: make clean
      - name: checking executables
        run: |
          while($EXECUTABLES != $string):
            do: 
              string=$( echo $EXECUTABLES | cut -d\; -f1 )
              if [ -x string]; then
              exit 1

  run_tests:
    needs: [check_program_compilation]
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v4
        with:
          fect-depth: 0
      - name: run tests
        timeout-minutes: 2
        run: make tests_run

  push_to_mirror:
    needs: [run_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fect-depth: 0